name: HTML Build and Deploy

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to 'main'
  
jobs:
  build:
    runs-on: amazonubuntu # Use the latest Ubuntu runner
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

      - name: Deploy to Amazon EC2 with Nginx

       run: | 
       cp . /var/www/html/
        # Restart Nginx to apply the new changes
          sudo systemctl restart nginx
        EOF
